(function(){
"use strict";
var KEY="sproutMarketGardenSave.v2";
var OLD_KEY="sproutMarketGardenSave.v1";
var MUTATIONS={gold:{name:"Gold",icon:"G",multi:5,cls:"mutation-gold"},rainbow:{name:"Rainbow",icon:"R",multi:10,cls:"mutation-rainbow"},wet:{name:"Wet",icon:"W",multi:2,cls:"mutation-wet"},frozen:{name:"Frozen",icon:"F",multi:3,cls:"mutation-frozen"},windblown:{name:"Windblown",icon:"A",multi:2.5,cls:"mutation-wind"},celestial:{name:"Celestial",icon:"C",multi:6,cls:"mutation-celestial"},moonlit:{name:"Moonlit",icon:"M",multi:4,cls:"mutation-moonlit"},shocked:{name:"Shocked",icon:"S",multi:10,cls:"mutation-shocked"}};
var WEATHER=[{id:"sunny",name:"Sunny",icon:"\u2600",mutation:null,desc:"Normal growing weather."},{id:"rain",name:"Rain",icon:"\u2614",mutation:"wet",desc:"Growing plants can become Wet."},{id:"frost",name:"Frost",icon:"\u2744",mutation:"frozen",desc:"Growing plants can become Frozen."},{id:"wind",name:"Windy",icon:"\u2197",mutation:"windblown",desc:"Growing plants can become Windblown."},{id:"meteor",name:"Meteor Shower",icon:"\u2726",mutation:"celestial",desc:"Growing plants can become Celestial."},{id:"thunderstorm",name:"Thunderstorm",icon:"\u26A1",mutation:"shocked",desc:"Growing plants can become Shocked."},{id:"night",name:"Night Time",icon:"\uD83C\uDF19",mutation:"moonlit",desc:"Night event weather. Growing plants can become Moonlit."}];
var WEATHER_MS=300000;
var HOUR_MS=3600000;
var NIGHT_WEATHER_MS=300000;
var SHOP_RESTOCK_MS=300000;
var GEAR_RESTOCK_MS=300000;
var EGG_RESTOCK_MS=600000;
var EVENT_RESTOCK_MS=600000;
var STOCK_RULES={Common:{chance:1,min:5,max:9},Uncommon:{chance:.82,min:3,max:6},Rare:{chance:.45,min:2,max:4},Epic:{chance:.22,min:1,max:3},Legendary:{chance:.09,min:1,max:2},Mythic:{chance:.025,min:1,max:1},Divine:{chance:.006,min:1,max:1},Prismatic:{chance:.0005,min:1,max:1}};
var NIGHT_EVENT_WEEK=25;
var NIGHT_OWL_MS=300000;
var PET_LEVEL_MAX=25;
var PET_EQUIP_MAX=4;
var PET_WALK_MS=8000;
var WEATHER_MUSIC={sunny:{wave:"triangle",notes:[262,330,392,523],gain:.045},rain:{wave:"sine",notes:[196,247,294,330],gain:.035},frost:{wave:"sine",notes:[220,277,370,440],gain:.03},wind:{wave:"sawtooth",notes:[174,220,261,349],gain:.025},meteor:{wave:"triangle",notes:[330,415,554,660],gain:.04},thunderstorm:{wave:"square",notes:[110,147,196,247],gain:.035},night:{wave:"sine",notes:[165,220,247,330],gain:.035}};
var music={ctx:null,master:null,osc:[],timer:0,step:0,ids:[],on:false};
var EVENT_ITEMS=[
{id:"moonblossom",kind:"seed",name:"Moon Blossom Seed",icon:"\uD83C\uDF19",cost:200000,chance:.005,desc:"Limited Divine event plant."},
{id:"nightOwl",kind:"pet",name:"Owl",icon:"\uD83E\uDD89",cost:500000,chance:.0025,desc:"Divine pet. Makes a plant Moonlit every 5 minutes."},
{id:"moonbloom",kind:"seed",name:"Moonbloom Seed",icon:"\uD83C\uDF11",cost:1000000,chance:.001,desc:"Limited Prismatic event plant."},
{id:"nightSeedPack",kind:"pack",name:"Night Seed Pack",icon:"\uD83C\uDF0C",cost:1000,chance:.75,min:2,max:5,desc:"Contains one limited night seed."}
];
var PETS={
bee:{name:"Honey Bee",icon:"🐝",rarity:"Common",desc:"Adds a small Gold mutation chance.",gold:.018},
butterfly:{name:"Garden Butterfly",icon:"🦋",rarity:"Common",desc:"Adds a small Rainbow mutation chance.",rainbow:.006},
snail:{name:"Sprout Snail",icon:"🐌",rarity:"Uncommon",desc:"Adds bonus harvest yield.",yield:1},
squirrel:{name:"Seed Squirrel",icon:"🐿",rarity:"Uncommon",desc:"Adds one extra harvest to multi-harvest crops.",harvests:1},
frog:{name:"Rain Frog",icon:"🐸",rarity:"Rare",desc:"Improves weather mutation chances.",weather:.08},
rabbit:{name:"Moon Rabbit",icon:"🐇",rarity:"Rare",desc:"Gives bonus coins from crop sales.",coins:.12},
fox:{name:"Golden Fox",icon:"🦊",rarity:"Epic",desc:"Boosts Gold mutations and crop sale coins.",gold:.04,coins:.18},
owl:{name:"Wise Owl",icon:"🦉",rarity:"Epic",desc:"Speeds up crop growth.",speed:.08},
turtle:{name:"Ancient Turtle",icon:"🐢",rarity:"Rare",desc:"Adds steady yield and sale coins.",yield:1,coins:.08},
hummingbird:{name:"Hummingbird",icon:"🐦",rarity:"Rare",desc:"Speeds up growth and improves Rainbow chances.",speed:.07,rainbow:.01},
peacock:{name:"Royal Peacock",icon:"🦚",rarity:"Epic",desc:"Improves weather mutations and sale coins.",weather:.1,coins:.16},
cat:{name:"Lucky Cat",icon:"🐈",rarity:"Epic",desc:"Boosts Gold mutations and harvest yield.",gold:.035,yield:1},
dragon:{name:"Prism Dragon",icon:"🐲",rarity:"Legendary",desc:"Boosts Rainbow mutations, growth, and yield.",rainbow:.025,speed:.1,yield:1},
unicorn:{name:"Crystal Unicorn",icon:"🦄",rarity:"Legendary",desc:"Greatly boosts Rainbow chances and bonus coins.",rainbow:.035,coins:.28},
griffin:{name:"Sun Griffin",icon:"🦅",rarity:"Legendary",desc:"Adds extra harvests and Gold mutation chance.",gold:.045,harvests:1},
phoenix:{name:"Aurora Phoenix",icon:"🔥",rarity:"Mythic",desc:"Adds many premium pet bonuses.",gold:.05,rainbow:.03,weather:.12,coins:.25,speed:.12,yield:2,harvests:1},
leviathan:{name:"Bloom Leviathan",icon:"🌊",rarity:"Mythic",desc:"Massively improves weather mutations and growth.",weather:.18,speed:.14,yield:2},
stardrake:{name:"Stardrake",icon:"🌟",rarity:"Prismatic",desc:"A top-tier pet with powerful all-around bonuses.",gold:.08,rainbow:.05,weather:.18,coins:.4,speed:.16,yield:3,harvests:2}
,nightOwl:{name:"Owl",icon:"\uD83E\uDD89",rarity:"Divine",desc:"Night event pet. Makes a plant Moonlit every 5 minutes."}
};
var EGGS=[
{id:"garden",name:"Garden Egg",icon:"🥚",cost:25000,stockChance:1,minStock:2,maxStock:4,desc:"Common pets with a chance for Uncommon.",pool:["bee","butterfly","snail","squirrel"]},
{id:"weather",name:"Weather Egg",icon:"🌦",cost:120000,stockChance:.8,minStock:1,maxStock:3,desc:"Pets that help weather mutations and farm value.",pool:["frog","rabbit","fox","owl","hummingbird"]},
{id:"orchard",name:"Orchard Egg",icon:"🍃",cost:220000,stockChance:.65,minStock:1,maxStock:2,desc:"Pets focused on yield, harvests, and steady coin gains.",pool:["snail","squirrel","turtle","cat","peacock"]},
{id:"royal",name:"Royal Egg",icon:"👑",cost:380000,stockChance:.42,minStock:1,maxStock:2,desc:"Epic and Legendary pets with strong garden bonuses.",pool:["fox","owl","peacock","cat","dragon","unicorn","griffin"]},
{id:"mythic",name:"Mythic Egg",icon:"🌌",cost:520000,stockChance:.24,minStock:1,maxStock:1,desc:"Powerful pets with Legendary and Mythic potential.",pool:["fox","owl","dragon","unicorn","griffin","phoenix","leviathan"]},
{id:"prism",name:"Prism Egg",icon:"💠",cost:1400000,stockChance:.08,minStock:1,maxStock:1,desc:"Very expensive egg with a chance at the rarest pets.",pool:["dragon","unicorn","griffin","phoenix","leviathan","stardrake"]}
];
var CROPS=[
{id:"carrot",name:"Carrot",icon:"🥕",seedCost:20,sell:24,grow:20000,unlock:0,rarity:"Common",multi:1,desc:"Fast starter crop"},
{id:"lemon",name:"Lemon",icon:"🍋",seedCost:95,sell:70,grow:50000,unlock:70,rarity:"Common",multi:2,regrow:.58,desc:"Bright citrus fruit with a second harvest"},
{id:"strawberry",name:"Strawberry",icon:"🍓",seedCost:140,sell:62,grow:42000,unlock:110,rarity:"Common",multi:3,regrow:.55,desc:"Sweet starter fruit that regrows twice"},
{id:"corn",name:"Corn",icon:"🌽",seedCost:150,sell:190,grow:75000,unlock:130,rarity:"Uncommon",multi:1,desc:"Reliable profit crop"},
{id:"apple",name:"Apple",icon:"🍎",seedCost:240,sell:130,grow:70000,unlock:190,rarity:"Uncommon",multi:3,regrow:.6,desc:"Orchard fruit with repeat harvests"},
{id:"blueberry",name:"Blueberry",icon:"🫐",seedCost:340,sell:105,grow:58000,unlock:260,rarity:"Uncommon",multi:4,regrow:.5,desc:"Berry bush with repeat harvests"},
{id:"cherry",name:"Cherry",icon:"🍒",seedCost:520,sell:150,grow:82000,unlock:390,rarity:"Uncommon",multi:4,regrow:.52,desc:"Small orchard fruit with several harvests"},
{id:"watermelon",name:"Watermelon",icon:"🍉",seedCost:300,sell:390,grow:98000,unlock:240,rarity:"Rare",multi:1,desc:"Juicy summer payout"},
{id:"banana",name:"Banana",icon:"🍌",seedCost:780,sell:320,grow:108000,unlock:590,rarity:"Rare",multi:3,regrow:.57,desc:"Tropical fruit that keeps producing"},
{id:"kiwi",name:"Kiwi",icon:"🥝",seedCost:920,sell:400,grow:128000,unlock:690,rarity:"Rare",multi:3,regrow:.56,desc:"Tangy vine fruit with repeat harvests"},
{id:"grape",name:"Grape",icon:"🍇",seedCost:1300,sell:310,grow:115000,unlock:980,rarity:"Rare",multi:5,regrow:.45,desc:"Vine crop with many harvests"},
{id:"pumpkin",name:"Pumpkin",icon:"🎃",seedCost:850,sell:1100,grow:160000,unlock:650,rarity:"Epic",multi:1,desc:"Slow, heavy payout"},
{id:"pineapple",name:"Pineapple",icon:"🍍",seedCost:1250,sell:820,grow:150000,unlock:940,rarity:"Epic",multi:2,regrow:.62,desc:"Tropical crop with a second harvest"},
{id:"peach",name:"Peach",icon:"🍑",seedCost:1700,sell:720,grow:135000,unlock:1280,rarity:"Epic",multi:3,regrow:.58,desc:"Soft orchard fruit with repeat harvests"},
{id:"papaya",name:"Papaya",icon:"🍈",seedCost:2600,sell:1050,grow:170000,unlock:1950,rarity:"Epic",multi:3,regrow:.56,desc:"Soft tropical fruit with strong repeat value"},
{id:"mango",name:"Mango",icon:"🥭",seedCost:4200,sell:1700,grow:180000,unlock:3150,rarity:"Legendary",multi:3,regrow:.6,desc:"Golden tropical tree with repeat harvests"},
{id:"bamboo",name:"Bamboo",icon:"🎍",seedCost:5200,sell:6500,grow:205000,unlock:3900,rarity:"Legendary",multi:1,desc:"Tall legendary stalk with a strong single harvest"},
{id:"pomegranate",name:"Pomegranate",icon:"🔴",seedCost:5600,sell:2200,grow:200000,unlock:4200,rarity:"Legendary",multi:3,regrow:.57,desc:"Jewel-toned fruit with premium harvests"},
{id:"cacao",name:"Cacao Pod",icon:"🍫",seedCost:7800,sell:3200,grow:230000,unlock:5850,rarity:"Legendary",multi:3,regrow:.6,desc:"Rich orchard pod for late gardens"},
{id:"starfruit",name:"Starfruit",icon:"⭐",seedCost:9000,sell:3600,grow:240000,unlock:6750,rarity:"Legendary",multi:3,regrow:.6,desc:"Premium garden treasure that regrows"},
{id:"dragonfruit",name:"Dragonfruit",icon:"🐉",seedCost:12500,sell:3800,grow:215000,unlock:9400,rarity:"Legendary",multi:4,regrow:.55,desc:"Exotic fruit with repeat premium harvests"},
{id:"moonmelon",name:"Moon Melon",icon:"🌙",seedCost:18000,sell:11000,grow:320000,unlock:13500,rarity:"Mythic",multi:2,regrow:.65,desc:"Rare night-blooming jackpot with a second harvest"},
{id:"durian",name:"Durian",icon:"🟤",seedCost:36000,sell:21000,grow:430000,unlock:27000,rarity:"Mythic",multi:2,regrow:.64,desc:"Huge mythic fruit with heavy payouts"},
{id:"sugarapple",name:"Sugar Apple",icon:"🍏",seedCost:48000,sell:19000,grow:380000,unlock:36000,rarity:"Mythic",multi:3,regrow:.62,desc:"Sweet high-tier tree with repeat harvests"},
{id:"lychee",name:"Lychee",icon:"🧺",seedCost:62000,sell:17000,grow:350000,unlock:46500,rarity:"Mythic",multi:4,regrow:.55,desc:"Delicate mythic fruit with repeat harvests"},
{id:"sunpear",name:"Sun Pear",icon:"🍐",seedCost:95000,sell:39000,grow:460000,unlock:71000,rarity:"Divine",multi:3,regrow:.58,desc:"Radiant divine orchard fruit"},
{id:"lotusfruit",name:"Lotus Fruit",icon:"🌸",seedCost:125000,sell:52000,grow:520000,unlock:94000,rarity:"Divine",multi:3,regrow:.58,desc:"Divine fruit with calm glowing petals"},
{id:"ambrosiaplum",name:"Ambrosia Plum",icon:"🟣",seedCost:210000,sell:86000,grow:630000,unlock:158000,rarity:"Divine",multi:3,regrow:.6,desc:"Luxurious divine fruit with huge value"},
{id:"crystalcoconut",name:"Crystal Coconut",icon:"🥥",seedCost:260000,sell:76000,grow:560000,unlock:195000,rarity:"Divine",multi:4,regrow:.55,desc:"Glittering divine palm fruit"},
{id:"prismberry",name:"Prism Berry",icon:"💎",seedCost:1200000,sell:310000,grow:680000,unlock:900000,rarity:"Prismatic",multi:5,regrow:.5,desc:"Prismatic berry that shines with stacked value"},
{id:"nebulaorange",name:"Nebula Orange",icon:"🍊",seedCost:1850000,sell:520000,grow:760000,unlock:1380000,rarity:"Prismatic",multi:4,regrow:.52,desc:"Cosmic citrus with prismatic value"},
{id:"aurorafruit",name:"Aurora Fruit",icon:"🌈",seedCost:2600000,sell:740000,grow:820000,unlock:1950000,rarity:"Prismatic",multi:4,regrow:.52,desc:"Ultimate prismatic fruit for elite gardens"},
{id:"infinityfig",name:"Infinity Fig",icon:"♾",seedCost:4200000,sell:1600000,grow:980000,unlock:3150000,rarity:"Prismatic",multi:3,regrow:.58,desc:"Extremely rare prismatic fruit for endgame gardens"},
{id:"candyapple",name:"Candy Apple",icon:"🍬",seedCost:0,sell:145,rarity:"Rare",grow:90000,unlock:0,multi:2,regrow:.55,packOnly:true,desc:"Seed pack exclusive sugar-glazed fruit"},
{id:"cloudberry",name:"Cloudberry",icon:"☁",seedCost:0,sell:420,rarity:"Epic",grow:150000,unlock:0,multi:3,regrow:.5,packOnly:true,desc:"Seed pack exclusive fruit grown from mist"},
{id:"emberfig",name:"Ember Fig",icon:"🔥",seedCost:0,sell:1250,rarity:"Legendary",grow:240000,unlock:0,multi:3,regrow:.55,packOnly:true,desc:"Seed pack exclusive fruit with warm sparks"},
{id:"royalkiwi",name:"Royal Kiwi",icon:"🥝",seedCost:0,sell:3600,rarity:"Divine",grow:420000,unlock:0,multi:4,regrow:.55,packOnly:true,desc:"Seed pack exclusive divine vine fruit"},
{id:"prismplum",name:"Prism Plum",icon:"🔮",seedCost:0,sell:9800,rarity:"Prismatic",grow:620000,unlock:0,multi:4,regrow:.5,packOnly:true,desc:"Seed pack exclusive prismatic orchard fruit"}
,{id:"moonblossom",name:"Moon Blossom",icon:"\uD83C\uDF19",seedCost:0,sell:78000,rarity:"Divine",grow:520000,unlock:0,multi:3,regrow:.58,packOnly:true,eventOnly:true,desc:"Night event Divine blossom"},
{id:"moonbloom",name:"Moonbloom",icon:"\uD83C\uDF11",seedCost:0,sell:320000,rarity:"Prismatic",grow:760000,unlock:0,multi:4,regrow:.52,packOnly:true,eventOnly:true,desc:"Night event Prismatic bloom"},
{id:"orchid",name:"Orchid",icon:"\uD83C\uDF3A",seedCost:0,sell:160,rarity:"Uncommon",grow:70000,unlock:0,multi:1,packOnly:true,eventOnly:true,desc:"Night Seed Pack flower"},
{id:"lavender",name:"Lavender",icon:"\uD83C\uDF38",seedCost:0,sell:420,rarity:"Rare",grow:110000,unlock:0,multi:1,packOnly:true,eventOnly:true,desc:"Night Seed Pack flower"},
{id:"mulberry",name:"Mulberry",icon:"\uD83C\uDF47",seedCost:0,sell:850,rarity:"Epic",grow:165000,unlock:0,multi:3,regrow:.55,packOnly:true,eventOnly:true,desc:"Night Seed Pack berry"},
{id:"nightshade",name:"Nightshade",icon:"\uD83C\uDF3F",seedCost:0,sell:3200,rarity:"Legendary",grow:240000,unlock:0,multi:2,regrow:.62,packOnly:true,eventOnly:true,desc:"Night Seed Pack legendary plant"},
{id:"blackapple",name:"Black Apple",icon:"\uD83C\uDF4E",seedCost:0,sell:14000,rarity:"Mythic",grow:360000,unlock:0,multi:3,regrow:.58,packOnly:true,eventOnly:true,desc:"Night Seed Pack mythic fruit"},
{id:"darkblossom",name:"Dark Blossom",icon:"\u2739",seedCost:0,sell:56000,rarity:"Divine",grow:520000,unlock:0,multi:4,regrow:.55,packOnly:true,eventOnly:true,desc:"Night Seed Pack Divine blossom"}
];
var GEAR=[
{id:"shovel",name:"Shovel",icon:"\u26CF",cost:24000,stockChance:1,minStock:3,maxStock:6,desc:"Removes a planted crop from any plot."},
{id:"wateringCan",name:"Watering Can",icon:"\uD83D\uDCA7",cost:38000,bundle:10,stockChance:1,minStock:2,maxStock:5,desc:"Cuts a planted crop's remaining growth time in half. Bought in bundles of 10."},
{id:"reclaimer",name:"Reclaimer",icon:"\u267B",cost:70000,stockChance:.75,minStock:1,maxStock:3,desc:"Removes a planted crop and gives that seed back."},
{id:"basicSprinkler",name:"Basic Sprinkler",icon:"\uD83D\uDCA6",cost:120000,stockChance:.6,minStock:1,maxStock:2,desc:"Waters a 3x3 plot area, speeds growth, slightly increases fruit size, and boosts mutation rates.",speed:.35,size:.2,mutation:.03,sprinkler:true},
{id:"advancedSprinkler",name:"Advanced Sprinkler",icon:"\uD83D\uDCA6",cost:420000,stockChance:.3,minStock:1,maxStock:1,desc:"Waters a 3x3 plot area with stronger growth, fruit size, and mutation boosts.",speed:.55,size:.45,mutation:.07,sprinkler:true},
{id:"masterSprinkler",name:"Master Sprinkler",icon:"\uD83D\uDCA6",cost:1250000,stockChance:.12,minStock:1,maxStock:1,desc:"Waters a 3x3 plot area with powerful growth, fruit size, and mutation boosts.",speed:.72,size:.85,mutation:.13,sprinkler:true}
];
var UPGRADE_MAX_LEVEL=50;
var UPGRADE_BASE_COST={plots:120,speed:95,yield:140};
var REBIRTH_BASE_COST=1000000;
var ADMIN_PASSWORD="NewRobloxSucks";
var adminUnlocked=false;
var starter={coins:40,rebirths:0,seeds:{},crops:{},gear:{shovel:0,wateringCan:0,reclaimer:0},pets:{},petLevels:{},equippedPets:[],petWalk:{},plots:[],up:{speed:0,yield:0,plots:0},selected:null,selectedType:null,musicOn:false,createdAt:Date.now(),lastSavedAt:Date.now(),daily:{date:"",quests:[]},stats:{plantedToday:0,coinsEarnedToday:0,seedsPlanted:0,coinsEarned:0},weather:{id:"sunny",nextAt:0},shop:{stock:{},slot:0,nextAt:0},gearShop:{stock:{},slot:0,nextAt:0},eggShop:{stock:{},slot:0,nextAt:0},eventShop:{stock:{},slot:0,nextAt:0},event:{owlNextAt:0},leaderboard:{name:"",rows:[],status:"Not submitted yet."}};
var state=load(),el={};
document.addEventListener("DOMContentLoaded",function(){["coins","plotsOwned","weatherNow","restocksNow","savedAt","selectedSeed","gardenGrid","petYard","shop","gearShop","petShop","inventory","quests","events","upgrades","rebirth","admin","leaderboard","refreshLeaderboard","log","saveGame","musicToggle","openAdmin","resetGame","sellAll","clearSeed","packModal","packTitle","packSubtitle","packCards","packClose","eggModal","eggTitle","eggSubtitle","eggResult","eggClose"].forEach(function(id){el[id]=document.getElementById(id)});setupTabs();el.saveGame.onclick=function(){save();say("Game saved.")};if(el.musicToggle)el.musicToggle.onclick=toggleMusic;if(el.openAdmin)el.openAdmin.onclick=function(){activateTab("adminPanel")};el.resetGame.onclick=function(){if(confirm("Reset your garden and erase saved progress?")){localStorage.removeItem(KEY);state=fresh();rollDaily();render();save();say("New garden started.")}};el.sellAll.onclick=sellAll;el.clearSeed.onclick=function(){state.selected=null;state.selectedType=null;render();save();say("Selection cleared.")};if(el.refreshLeaderboard)el.refreshLeaderboard.onclick=loadLeaderboard;if(el.packClose)el.packClose.onclick=closeSeedPack;if(el.eggClose)el.eggClose.onclick=closeEgg;fitPlots();rollDaily();render();setInterval(tick,1000);setInterval(save,5000);addEventListener("beforeunload",save)});
function setupTabs(){document.querySelectorAll(".tab-button").forEach(function(button){button.addEventListener("click",function(){activateTab(button.getAttribute("data-tab"))});});}
function activateTab(target){document.querySelectorAll(".tab-button").forEach(function(button){button.classList.toggle("active",button.getAttribute("data-tab")===target)});document.querySelectorAll(".tab-panel").forEach(function(panel){panel.classList.toggle("active",panel.id===target)});}
function fresh(){return JSON.parse(JSON.stringify(starter))}
function today(){return new Date().toISOString().slice(0,10)}
function load(){var s=fresh(),raw=localStorage.getItem(KEY)||localStorage.getItem(OLD_KEY);if(!raw)return s;try{var old=JSON.parse(raw);var m=Object.assign(s,old);m.seeds=Object.assign({},s.seeds,old.seeds||{});m.crops=Object.assign({},s.crops,old.crops||{});m.gear=Object.assign({},s.gear,old.gear||{});m.pets=Object.assign({},s.pets,old.pets||{});m.petLevels=Object.assign({},s.petLevels,old.petLevels||{});m.equippedPets=Array.isArray(old.equippedPets)?old.equippedPets.slice(0,PET_EQUIP_MAX):[];m.petWalk=Object.assign({},s.petWalk,old.petWalk||{});m.up=Object.assign({},s.up,old.up||{});m.stats=Object.assign({},s.stats,old.stats||{});m.daily=Object.assign({},s.daily,old.daily||{});m.weather=Object.assign({},s.weather,old.weather||{});m.shop=Object.assign({},s.shop,old.shop||{});m.shop.stock=Object.assign({},s.shop.stock,(old.shop&&old.shop.stock)||{});m.gearShop=Object.assign({},s.gearShop,old.gearShop||{});m.gearShop.stock=Object.assign({},s.gearShop.stock,(old.gearShop&&old.gearShop.stock)||{});m.eggShop=Object.assign({},s.eggShop,old.eggShop||{});m.eggShop.stock=Object.assign({},s.eggShop.stock,(old.eggShop&&old.eggShop.stock)||{});m.eventShop=Object.assign({},s.eventShop,old.eventShop||{});m.eventShop.stock=Object.assign({},s.eventShop.stock,(old.eventShop&&old.eventShop.stock)||{});m.event=Object.assign({},s.event,old.event||{});m.leaderboard=Object.assign({},s.leaderboard,old.leaderboard||{});m.plots=Array.isArray(old.plots)?old.plots:[];Object.keys(m.pets||{}).forEach(function(id){if((m.pets[id]||0)>0&&!m.petLevels[id])m.petLevels[id]=1});m.equippedPets=normalizeEquippedPets(m.equippedPets,m.pets);if(!Array.isArray(old.equippedPets))m.equippedPets=autoEquipPets(m.equippedPets,m.pets);if(m.coins===24&&!Object.keys(m.seeds||{}).length&&!Object.keys(m.crops||{}).length)m.coins=40;return m}catch(e){console.warn(e);return s}}
function save(){state.lastSavedAt=Date.now();localStorage.setItem(KEY,JSON.stringify(state));if(el.savedAt)el.savedAt.textContent="Now"}
function weatherById(id){return WEATHER.find(function(w){return w.id===id})||WEATHER[0]}
function activeNightEvent(){return eventWeek()===NIGHT_EVENT_WEEK}
function hourProgress(){return Date.now()%HOUR_MS}
function activeNightWeather(){return activeNightEvent()&&hourProgress()<NIGHT_WEATHER_MS}
function weatherSlot(){return Math.floor(Date.now()/WEATHER_MS)}
function sharedWeatherPool(){return WEATHER.filter(function(w){return w.id!=="night"&&w.id!=="sunny"})}
function sharedWeatherEvent(slot,index){var choices=sharedWeatherPool(),id=choices[Math.floor(stockRoll(slot,"weather_"+index,41)*choices.length)].id,duration=stockRoll(slot,"weather_len_"+index,73)<.5?1:2;return {id:id,until:(slot+duration)*WEATHER_MS}}
function sharedWeatherIds(slot){var ids=[],primary=sharedWeatherEvent(slot,0),prev=sharedWeatherEvent(slot-1,0);if(Date.now()<prev.until)ids.push(prev.id);ids.push(primary.id);if(stockRoll(slot,"weather_second",97)<.4){var second=sharedWeatherEvent(slot,1);if(ids.indexOf(second.id)<0)ids.push(second.id)}return ids.slice(0,2)}
function activeWeatherIds(){var ids=sharedWeatherIds(weatherSlot());if(activeNightWeather()){ids=ids.filter(function(id){return id!=="night"});ids.unshift("night")}return ids.slice(0,2)}
function rollWeather(){if(!state.weather)state.weather={id:"sunny",ids:["sunny"],nextAt:0};var ids=activeWeatherIds(),slot=weatherSlot();if(!ids.length)ids=["sunny"];state.weather.id=ids[0];state.weather.ids=ids;state.weather.nextAt=(slot+1)*WEATHER_MS;return weatherById(ids[0])}
function activeWeather(){return rollWeather()}
function activeWeatherMutations(){rollWeather();return (state.weather.ids||[state.weather.id]).map(function(id){return weatherById(id).mutation}).filter(Boolean)}
function addMutation(list,id){if(!id)return list||[];list=Array.isArray(list)?list:[];if(list.indexOf(id)<0)list.push(id);return list}
function maybeAddMutation(list,id,chance){if(id&&Math.random()<chance)addMutation(list,id);return list}
function mutationValue(muts){muts=Array.isArray(muts)?muts:[];return muts.reduce(function(total,id){return total*(MUTATIONS[id]?MUTATIONS[id].multi:1)},1)}
function mutationLabel(muts){muts=Array.isArray(muts)?muts:[];return muts.map(function(id){return MUTATIONS[id]?MUTATIONS[id].name:""}).filter(Boolean).join(" + ")}
function mutationBadges(muts){muts=Array.isArray(muts)?muts:[];return muts.map(function(id){var m=MUTATIONS[id];return m?"<span class='mutation-badge "+m.cls+"'>"+m.name+"</span>":""}).join("")}
function rollWeight(c,boost){var base={Common:1,Uncommon:1.15,Rare:1.35,Epic:1.6,Legendary:2,Mythic:2.6,Divine:3.4,Prismatic:4.4}[c.rarity]||1;var swing=.55+Math.random()*1.7;if(Math.random()<.08)swing+=Math.random()*1.5;if(Math.random()<.015)swing+=2+Math.random()*2.5;return Math.max(.2,Math.round(base*swing*(1+(Number(boost)||0))*10)/10)}
function weightMultiplier(w){w=Number(w)||1;return Math.max(.25,Math.round((.65+Math.pow(w,.72)*.35)*100)/100)}
function weightLabel(w){w=Number(w)||1;return w.toFixed(1)+" lb"}
function inventoryKey(id,muts,weight){muts=Array.isArray(muts)?muts.slice().sort():[];var parts=[id];if(muts.length)parts.push(muts.join("_"));if(weight)parts.push("w"+Number(weight).toFixed(1));return parts.join("__")}
function parseInventoryKey(key){var parts=String(key).split("__"),muts=[],weight=1;parts.slice(1).forEach(function(part){if(part.charAt(0)==="w")weight=Number(part.slice(1))||1;else muts=part.split("_").filter(Boolean)});return {id:parts[0],mutations:muts,weight:weight}}
function cropDisplayName(c,muts){var label=mutationLabel(muts);return label?label+" "+c.name:c.name}
function crop(id){return CROPS.find(function(c){return c.id===id})}
function gear(id){return GEAR.find(function(g){return g.id===id})}
function rarityRank(rarity){return ["Common","Uncommon","Rare","Epic","Legendary","Mythic","Divine","Prismatic"].indexOf(rarity)}
function unlockCost(c){return c.unlock===0?0:c.seedCost}
function clampUpgradeLevel(level){return Math.min(UPGRADE_MAX_LEVEL,Math.max(0,Number(level)||0))}
function upgradeCost(type,nextLevel){var base=UPGRADE_BASE_COST[type]||100;var curve={plots:1.24,speed:1.2,yield:1.22}[type]||1.2;return Math.round(base*Math.pow(curve,nextLevel-1)+nextLevel*12)}
function upgradeEffectText(type,data){if(type==="plots")return data.count+" total plots";if(type==="speed")return Math.round((1-data.multi)*100)+"% faster growth";return "+"+data.bonus+" crops per harvest"}
function makeUpgrade(type,level){level=clampUpgradeLevel(level);var data={level:level,max:UPGRADE_MAX_LEVEL,label:"Level "+level+" / "+UPGRADE_MAX_LEVEL,cost:level>0?upgradeCost(type,level):0};if(type==="plots")data.count=12+level;if(type==="speed")data.multi=Math.max(.2,1-level*.016);if(type==="yield")data.bonus=Math.floor(level/2);data.effect=upgradeEffectText(type,data);return data}
function up(type){state.up[type]=clampUpgradeLevel(state.up[type]);return makeUpgrade(type,state.up[type])}
function next(type){var level=clampUpgradeLevel(state.up[type]);return level>=UPGRADE_MAX_LEVEL?null:makeUpgrade(type,level+1)}
function plotLimit(){return up("plots").count}
function rebirthCount(){state.rebirths=Math.max(0,Math.floor(Number(state.rebirths)||0));return state.rebirths}
function rebirthCost(){return REBIRTH_BASE_COST*Math.pow(1000,rebirthCount())}
function rebirthSaleMultiplier(){return 1+rebirthCount()}
function cropSaleValue(c,muts,weight){return Math.round(c.sell*mutationValue(muts)*weightMultiplier(weight)*(1+petBonuses().coins)*rebirthSaleMultiplier())}
function normalizeEquippedPets(list,pets){var used={},out=[];(list||[]).forEach(function(id){if(out.length>=PET_EQUIP_MAX)return;var owned=(pets&&pets[id])||0;if(!PETS[id]||owned<1)return;used[id]=used[id]||0;if(used[id]>=owned)return;used[id]++;out.push(id)});return out}
function autoEquipPets(list,pets){var out=normalizeEquippedPets(list,pets),used={};out.forEach(function(id){used[id]=(used[id]||0)+1});Object.keys(pets||{}).forEach(function(id){var count=pets[id]||0;if(!PETS[id])return;for(var i=used[id]||0;i<count&&out.length<PET_EQUIP_MAX;i++)out.push(id)});return out}
function equippedCount(id){return (state.equippedPets||[]).filter(function(petId){return petId===id}).length}
function activePetCounts(){var counts={};state.equippedPets=normalizeEquippedPets(state.equippedPets,state.pets);(state.equippedPets||[]).forEach(function(id){counts[id]=(counts[id]||0)+1});return counts}
function equipPet(id){if(!PETS[id]||!(state.pets&&state.pets[id])){say("You do not own that pet.");return}state.equippedPets=normalizeEquippedPets(state.equippedPets,state.pets);if(state.equippedPets.length>=PET_EQUIP_MAX){say("Only "+PET_EQUIP_MAX+" pets can be equipped at once.");return}if(equippedCount(id)>=(state.pets[id]||0)){say("All of your "+PETS[id].name+" pets are already equipped.");return}state.equippedPets.push(id);render();save();say("Equipped "+PETS[id].name+".")}
function unequipPet(id){state.equippedPets=normalizeEquippedPets(state.equippedPets,state.pets);var index=state.equippedPets.indexOf(id);if(index<0){say(PETS[id].name+" is already in your inventory.");return}state.equippedPets.splice(index,1);render();save();say("Moved "+PETS[id].name+" to pet inventory.")}
function petLevel(id){return Math.max(1,Math.min(PET_LEVEL_MAX,Math.floor((state.petLevels&&state.petLevels[id])||((state.pets&&state.pets[id])?1:0))))}
function petScale(id){return 1+(petLevel(id)-1)*.12}
function petCooldownScale(id){return Math.max(.35,1-(petLevel(id)-1)*.04)}
function petBonuses(){var b={gold:0,rainbow:0,weather:0,coins:0,speed:0,yield:0,harvests:0},counts=activePetCounts();Object.keys(counts).forEach(function(id){var count=counts[id]||0,p=PETS[id],scale=petScale(id);if(!p||!count)return;["gold","rainbow","weather","coins","speed"].forEach(function(k){b[k]+=(p[k]||0)*count*scale});["yield","harvests"].forEach(function(k){b[k]+=Math.floor((p[k]||0)*count*scale)})});b.speed=Math.min(.45,b.speed);b.coins=Math.min(1.5,b.coins);b.gold=Math.min(.35,b.gold);b.rainbow=Math.min(.18,b.rainbow);b.weather=Math.min(.45,b.weather);return b}
function growMs(c){return Math.max(4000,Math.round(c.grow*up("speed").multi*(1-petBonuses().speed)))}
function fitPlots(){while(state.plots.length<plotLimit())state.plots.push(null);if(state.plots.length>plotLimit())state.plots=state.plots.slice(0,plotLimit())}
function tick(){rollWeather();ensureShopStock();ensureGearStock();ensureEggStock();ensureEventStock();movePets();applyNightOwl();applyWeatherMutations();drawPlots();drawPets();drawShop();drawGearShop();drawPetShop();drawEvents();stats()}
function render(){fitPlots();rollDaily();rollWeather();ensureShopStock();ensureGearStock();ensureEggStock();ensureEventStock();movePets();applyWeatherMutations();stats();drawSelected();drawPlots();drawPets();drawShop();drawGearShop();drawPetShop();drawInv();drawQuests();drawEvents();drawUpgrades();drawRebirth();drawAdmin();drawLeaderboard()}
function stats(){rollWeather();var ids=(state.weather&&state.weather.ids)||[state.weather&&state.weather.id],names=ids.map(function(id){var w=weatherById(id);return w.icon+" "+w.name}).join(" + ");el.coins.textContent=num(state.coins);el.plotsOwned.textContent=plotLimit();if(el.weatherNow)el.weatherNow.textContent=names||"\u2600 Sunny";if(el.restocksNow)el.restocksNow.textContent="Seeds "+time(state.shop.nextAt-Date.now())+" / Event "+time(state.eventShop.nextAt-Date.now());setMusicButton()}
function setMusicButton(){if(!el.musicToggle)return;el.musicToggle.textContent=music.on?"Music On":"Music Off";el.musicToggle.classList.toggle("active",music.on)}
function ensureMusic(){if(music.ctx)return true;var Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx){say("Music is not supported in this browser.");return false}music.ctx=new Ctx();music.master=music.ctx.createGain();music.master.gain.value=.22;music.master.connect(music.ctx.destination);return true}
function toggleMusic(){if(music.on){stopMusic();state.musicOn=false;save();say("Weather music off.");return}if(!ensureMusic())return;music.ctx.resume();music.on=true;state.musicOn=true;setMusicButton();playMusicStep();music.timer=setInterval(playMusicStep,850);save();say("Weather music on.")}
function stopMusic(){music.on=false;if(music.timer)clearInterval(music.timer);music.timer=0;setMusicButton()}
function playWeatherNote(id,lane){if(!music.on||!music.ctx||!music.master)return;var theme=WEATHER_MUSIC[id]||WEATHER_MUSIC.sunny,notes=theme.notes,note=notes[(music.step+lane*2)%notes.length],now=music.ctx.currentTime,osc=music.ctx.createOscillator(),gain=music.ctx.createGain(),laneGain=lane ? .65 : 1;osc.type=theme.wave;osc.frequency.setValueAtTime(note*(lane?1.5:1),now);gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(theme.gain*laneGain,now+.05);gain.gain.exponentialRampToValueAtTime(.0001,now+.78);osc.connect(gain);gain.connect(music.master);osc.start(now);osc.stop(now+.82)}
function playMusicStep(){rollWeather();var ids=((state.weather&&state.weather.ids)||["sunny"]).slice(0,2);ids.forEach(function(id,lane){playWeatherNote(id,lane)});music.step++}
function readyMutationRoll(p){if(!p||p.readyMutationDone)return;p.readyMutationDone=true;var pb=petBonuses(),boost=p.mutationBoost||0,weatherMuts=activeWeatherMutations();maybeAddMutation(p.mutations,"gold",.08+pb.gold+boost*.15);maybeAddMutation(p.mutations,"rainbow",.02+pb.rainbow+boost*.06);weatherMuts.forEach(function(mutation){maybeAddMutation(p.mutations,mutation,.28+pb.weather+boost)});}
function applyWeatherMutations(){var weatherMuts=activeWeatherMutations(),pb=petBonuses();state.plots.forEach(function(p){if(!p)return;var c=crop(p.id);if(!c)return;var boost=p.mutationBoost||0,progress=(Date.now()-p.at)/(p.duration||growMs(c));if(progress>=1){readyMutationRoll(p);return}if(progress>.2){maybeAddMutation(p.mutations,"gold",boost*.18);maybeAddMutation(p.mutations,"rainbow",boost*.055);weatherMuts.forEach(function(mutation){maybeAddMutation(p.mutations,mutation,.035+pb.weather+boost)})}});}
function drawSelected(){if(state.selectedType==="gear"){var g=gear(state.selected);el.selectedSeed.textContent=g?g.icon+" "+g.name+" selected":"No seed or gear selected";return}var c=crop(state.selected);el.selectedSeed.textContent=c?c.icon+" "+c.name+" selected":"No seed or gear selected"}
function drawPlots(){el.gardenGrid.innerHTML="";state.plots.forEach(function(p,i){var b=document.createElement("button");b.className="plot";b.type="button";b.onclick=function(){plotClick(i)};b.innerHTML="<span class='crop'></span><span class='plot-name'></span><span class='plot-mutations'></span><span class='plot-action'></span><span class='plot-time'></span><span class='progress'><i></i></span>";var ic=b.querySelector(".crop"),nm=b.querySelector(".plot-name"),mb=b.querySelector(".plot-mutations"),ac=b.querySelector(".plot-action"),tm=b.querySelector(".plot-time");if(!p){b.classList.add("empty");nm.textContent="Empty Plot";ac.textContent=state.selectedType==="seed"?"Plant":"Empty";tm.textContent=state.selectedType==="seed"?"Plant selected seed":"Select a seed"}else{var c=crop(p.id);if(!c){state.plots[i]=null;return}var d=p.duration||growMs(c),done=Math.min(1,Math.max(0,(Date.now()-p.at)/d));b.classList.toggle("ready",done>=1);b.style.setProperty("--progress",Math.round(done*100)+"%");ic.style.setProperty("--scale",String(.35+done*.75));ic.textContent=c.icon;nm.textContent=c.name;mb.innerHTML=mutationBadges(p.mutations);(p.mutations||[]).forEach(function(id){var m=MUTATIONS[id];if(m)b.classList.add(m.cls)});ac.textContent=state.selectedType==="gear"?"Use Gear":done>=1?"Harvest":"Growing";tm.textContent=(done>=1?(p.harvestsLeft>1?"Ready - "+p.harvestsLeft+" harvests left":"Ready to harvest"):time(d-(Date.now()-p.at)))+(p.sizeBoost?" - Size +"+Math.round(p.sizeBoost*100)+"%":"")+(p.mutationBoost?" - Mut +"+Math.round(p.mutationBoost*100)+"%":"")}el.gardenGrid.appendChild(b)})}
function ownedPetEntries(){var entries=[],seen={};state.equippedPets=normalizeEquippedPets(state.equippedPets,state.pets);(state.equippedPets||[]).forEach(function(id){var p=PETS[id];if(!p)return;seen[id]=seen[id]||0;entries.push({key:id+"-"+seen[id],id:id,pet:p,level:petLevel(id),extra:0});seen[id]++});return entries}
function movePets(){if(!state.petWalk)state.petWalk={};var now=Date.now();ownedPetEntries().forEach(function(entry,index){var spot=state.petWalk[entry.key];if(!spot){spot={x:12+(index*17)%76,y:20+(index*23)%66,nextAt:0,restUntil:0}}if(now>=spot.nextAt&&now>=spot.restUntil){var resting=stockRoll(Math.floor(now/PET_WALK_MS),entry.key,211)<.35;spot.x=8+Math.floor(stockRoll(Math.floor(now/PET_WALK_MS),entry.key,31)*84);spot.y=18+Math.floor(stockRoll(Math.floor(now/PET_WALK_MS),entry.key,47)*70);spot.restUntil=resting?now+PET_WALK_MS:0;spot.nextAt=now+PET_WALK_MS+(index%4)*650}state.petWalk[entry.key]=spot})}
function drawPets(){if(!el.petYard)return;movePets();el.petYard.innerHTML="";ownedPetEntries().forEach(function(entry){var spot=state.petWalk&&state.petWalk[entry.key]||{x:50,y:50},node=document.createElement("div");node.className="yard-pet rarity-"+entry.pet.rarity.toLowerCase();node.style.left=spot.x+"%";node.style.top=spot.y+"%";node.innerHTML="<span>"+entry.pet.icon+"</span><small>Lv "+entry.level+(entry.extra?"+":"")+"</small>";node.title=entry.pet.name+" Lv "+entry.level+(spot.restUntil>Date.now()?" resting":" walking");el.petYard.appendChild(node)})}
function plotClick(i){var p=state.plots[i];if(state.selectedType==="gear"){useGear(i);return}if(!p){plant(i);return}if(Date.now()-p.at>=p.duration){harvest(i);return}say("That crop is still growing.")}
function plant(i){var c=crop(state.selected);if(!c||state.selectedType!=="seed"){say("Choose a seed first.");return}if((state.seeds[c.id]||0)<1){state.selected=null;state.selectedType=null;render();say("You do not have any "+c.name+" seeds.");return}state.seeds[c.id]--;var muts=[];var pb=petBonuses();maybeAddMutation(muts,"gold",.05+pb.gold);maybeAddMutation(muts,"rainbow",.012+pb.rainbow);activeWeatherMutations().forEach(function(mutation){maybeAddMutation(muts,mutation,.18+pb.weather)});var harvestCount=(c.multi||1)+pb.harvests;state.plots[i]={id:c.id,at:Date.now(),duration:growMs(c),harvestsLeft:harvestCount,totalHarvests:harvestCount,mutations:muts,readyMutationDone:false};state.stats.plantedToday++;state.stats.seedsPlanted++;render();save();say("Planted "+c.name+".")}
function harvest(i){var p=state.plots[i],c=crop(p.id);readyMutationRoll(p);var amt=1+up("yield").bonus+petBonuses().yield,weight=rollWeight(c,p.sizeBoost),key=inventoryKey(c.id,p.mutations,weight);state.crops[key]=(state.crops[key]||0)+amt;p.sizeBoost=0;p.mutationBoost=0;p.speedBoost=0;p.harvestsLeft=p.harvestsLeft||1;p.harvestsLeft--;if(p.harvestsLeft>0){p.at=Date.now();p.duration=Math.max(4000,Math.round(growMs(c)*(c.regrow||.6)));p.readyMutationDone=false;p.totalHarvests=p.totalHarvests||c.multi||1;say("Harvested "+amt+" "+weightLabel(weight)+" "+c.name+". The plant will regrow for "+p.harvestsLeft+" more harvest"+(p.harvestsLeft===1?"":"s")+".");}else{state.plots[i]=null;say("Harvested "+amt+" "+weightLabel(weight)+" "+c.name+".");}render();save();pulse(el.inventory)}
function gridCols(){var first=el.gardenGrid&&el.gardenGrid.querySelector(".plot");if(!first)return Math.max(1,Math.round(Math.sqrt(plotLimit())));return Math.max(1,Math.round(el.gardenGrid.clientWidth/first.getBoundingClientRect().width))}
function nearbyPlots(i){var cols=gridCols(),row=Math.floor(i/cols),col=i%cols,spots=[];for(var r=row-1;r<=row+1;r++)for(var c=col-1;c<=col+1;c++){var idx=r*cols+c;if(r>=0&&c>=0&&idx>=0&&idx<state.plots.length&&Math.floor(idx/cols)===r)spots.push(idx)}return spots}
function speedPlot(p,factor){var now=Date.now(),elapsed=now-p.at,remaining=Math.max(1000,(p.duration||0)-elapsed);p.duration=elapsed+Math.ceil(remaining*(1-factor));p.speedBoost=0}
function useSprinkler(i,g){var count=0;nearbyPlots(i).forEach(function(idx){var p=state.plots[idx];if(!p)return;speedPlot(p,g.speed);p.sizeBoost=Math.min(3,(p.sizeBoost||0)+g.size);p.mutationBoost=Math.min(.65,(p.mutationBoost||0)+(g.mutation||0));count++});if(!count){say(g.name+" needs at least one planted crop in its 3x3 area.");return false}say(g.name+" watered "+count+" plant"+(count===1?"":"s")+", boosting growth, fruit size, and mutation rates.");return true}
function useGear(i){var g=gear(state.selected),p=state.plots[i];if(!g){say("Select gear first.");return}if(!p&&!g.sprinkler){say(g.name+" needs a planted plot.");return}if((state.gear[g.id]||0)<1){state.selected=null;state.selectedType=null;render();say("You do not have any "+g.name+" left.");return}var used=true;if(g.sprinkler)used=useSprinkler(i,g);else if(g.id==="shovel"){state.plots[i]=null;say("Removed the plant with a Shovel.")}else if(g.id==="reclaimer"){state.seeds[p.id]=(state.seeds[p.id]||0)+1;state.plots[i]=null;say("Reclaimed the plant and recovered a "+crop(p.id).name+" seed.")}else if(g.id==="wateringCan"){speedPlot(p,.5);say("Watering Can sped up the crop.")}if(!used)return;state.gear[g.id]--;render();save()}
function shopSlot(){return Math.floor(Date.now()/SHOP_RESTOCK_MS)}
function slotEnd(slot){return (slot+1)*SHOP_RESTOCK_MS}
function eventShopSlot(){return Math.floor(Date.now()/EVENT_RESTOCK_MS)}
function eventSlotEnd(slot){return (slot+1)*EVENT_RESTOCK_MS}
function seededRand(seed){var t=seed+0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296}
function stockRoll(slot,id,salt){var seed=slot;for(var i=0;i<id.length;i++)seed=Math.imul(seed^id.charCodeAt(i),2654435761);return seededRand(seed+(salt||0))}
function restockAmount(rarity,slot,id){var r=STOCK_RULES[rarity]||STOCK_RULES.Common;return r.min+Math.floor(stockRoll(slot,id,991)*(r.max-r.min+1))}
function rollShopStock(slot){slot=slot||shopSlot();var stock={};CROPS.forEach(function(c){if(c.packOnly)return;var r=STOCK_RULES[c.rarity]||STOCK_RULES.Common;if(stockRoll(slot,c.id,17)<r.chance)stock[c.id]=restockAmount(c.rarity,slot,c.id)});if(!stock.carrot)stock.carrot=restockAmount("Common",slot,"carrot");state.shop={stock:stock,slot:slot,nextAt:slotEnd(slot)};return stock}
function ensureShopStock(){if(!state.shop)state.shop={stock:{},slot:0,nextAt:0};if(!state.shop.stock)state.shop.stock={};var slot=shopSlot();if(state.shop.slot!==slot||!state.shop.nextAt){rollShopStock(slot);save();say("Seed Shop restocked.")}}
function stockLeft(id){ensureShopStock();return state.shop.stock[id]||0}
function gearSlot(){return Math.floor(Date.now()/GEAR_RESTOCK_MS)}
function gearSlotEnd(slot){return (slot+1)*GEAR_RESTOCK_MS}
function eggSlot(){return Math.floor(Date.now()/EGG_RESTOCK_MS)}
function eggSlotEnd(slot){return (slot+1)*EGG_RESTOCK_MS}
function limitedAmount(item,slot,prefix){var min=item.minStock||1,max=item.maxStock||min;return min+Math.floor(stockRoll(slot,prefix+item.id,113)*(max-min+1))}
function rollGearStock(slot){slot=slot||gearSlot();var stock={};GEAR.forEach(function(g){if(stockRoll(slot,"gear_"+g.id,53)<(g.stockChance||1))stock[g.id]=limitedAmount(g,slot,"gear_amt_")});state.gearShop={stock:stock,slot:slot,nextAt:gearSlotEnd(slot)};return stock}
function ensureGearStock(){if(!state.gearShop)state.gearShop={stock:{},slot:0,nextAt:0};if(!state.gearShop.stock)state.gearShop.stock={};var slot=gearSlot();if(state.gearShop.slot!==slot||!state.gearShop.nextAt){rollGearStock(slot);save();say("Gear Shop restocked.")}}
function gearStockLeft(id){ensureGearStock();return state.gearShop.stock[id]||0}
function rollEggStock(slot){slot=slot||eggSlot();var stock={};EGGS.forEach(function(egg){if(stockRoll(slot,"egg_"+egg.id,67)<(egg.stockChance||1))stock[egg.id]=limitedAmount(egg,slot,"egg_amt_")});state.eggShop={stock:stock,slot:slot,nextAt:eggSlotEnd(slot)};return stock}
function ensureEggStock(){if(!state.eggShop)state.eggShop={stock:{},slot:0,nextAt:0};if(!state.eggShop.stock)state.eggShop.stock={};var slot=eggSlot();if(state.eggShop.slot!==slot||!state.eggShop.nextAt){rollEggStock(slot);save();say("Pet Shop eggs restocked.")}}
function eggStockLeft(id){ensureEggStock();return state.eggShop.stock[id]||0}
function addPet(id){if(!state.pets)state.pets={};if(!state.petLevels)state.petLevels={};if(!state.equippedPets)state.equippedPets=[];state.pets[id]=(state.pets[id]||0)+1;state.petLevels[id]=Math.min(PET_LEVEL_MAX,Math.max(1,state.petLevels[id]||1)+(state.pets[id]>1?1:0));state.equippedPets=normalizeEquippedPets(state.equippedPets,state.pets);if(state.equippedPets.length<PET_EQUIP_MAX)state.equippedPets.push(id)}
function drawShop(){ensureShopStock();el.shop.innerHTML="";var timer=row("\u23F1","Seed Shop Restock: "+time(state.shop.nextAt-Date.now()),"New limited stock arrives every 5 minutes. Rarer seeds appear less often; Prismatic seeds have a 0.05% stock chance.");timer.classList.add("restock-item");el.shop.appendChild(timer);CROPS.filter(function(c){return !c.packOnly}).slice().sort(function(a,b){return rarityRank(a.rarity)-rarityRank(b.rarity)||a.seedCost-b.seedCost||a.name.localeCompare(b.name)}).forEach(function(c){var available=stockLeft(c.id),need=unlockCost(c),unlocked=state.coins>=need||need===0||(state.seeds[c.id]||0)>0||(state.crops[c.id]||0)>0;var stocked=available>0,canBuy=unlocked&&stocked&&state.coins>=c.seedCost;var meta=unlocked?c.rarity+" - Stock: "+available+" - "+c.desc+" - "+((c.multi||1)>1?c.multi+" harvests - ":"")+"grows in "+time(growMs(c))+" - sells for "+num(c.sell):"Unlock when you reach "+num(need)+" coins.";if(!stocked)meta=unlocked?c.rarity+" - Out of stock until next restock.":meta;var item=row(c.icon,c.name+" Seed",meta,c.rarity);item.querySelector(".actions").append(btn(!unlocked?"Locked":stocked?"Buy "+num(c.seedCost):"Out",!canBuy,function(){buySeed(c.id,1)}),btn("Quick Buy",!canBuy,function(){quickBuySeed(c.id)}),btn("Select",(state.seeds[c.id]||0)<1,function(){selectSeed(c.id)}));el.shop.appendChild(item)})}
function drawGearShop(){ensureGearStock();el.gearShop.innerHTML="";var timer=row("\u23F1","Gear Shop Restock: "+time(state.gearShop.nextAt-Date.now()),"Shared limited gear stock refreshes every 5 minutes.");timer.classList.add("restock-item");el.gearShop.appendChild(timer);GEAR.forEach(function(g){var stock=gearStockLeft(g.id),canBuy=stock>0&&state.coins>=g.cost,bundle=g.bundle||1,bundleText=bundle>1?" - Bundle: "+bundle:"";var item=row(g.icon,g.name,g.desc+" Cost: "+num(g.cost)+" coins"+bundleText+" - Stock: "+stock+" - Owned: "+(state.gear[g.id]||0));item.querySelector(".actions").append(btn(stock>0?"Buy "+(bundle>1?bundle+" for ":"")+num(g.cost):"Out",!canBuy,function(){buyGear(g.id,1)}),btn("Quick Buy",!canBuy,function(){quickBuyGear(g.id)}),btn("Select",(state.gear[g.id]||0)<1,function(){selectGear(g.id)}));el.gearShop.appendChild(item)})}
function quickBuySeed(id){var c=crop(id),available=stockLeft(id),affordable=Math.floor(state.coins/c.seedCost),max=Math.min(available,affordable);if(max<1){say("You cannot buy any "+c.name+" seeds right now.");return}var raw=prompt("How many "+c.name+" seeds do you want to buy? Max: "+max,max);if(raw===null)return;var qty=Math.floor(Number(raw));if(!qty||qty<1){say("Quick buy cancelled.");return}buySeed(id,qty)}
function buySeed(id,qty){var c=crop(id);ensureShopStock();qty=Math.max(1,Math.floor(Number(qty)||1));var available=stockLeft(id),affordable=Math.floor(state.coins/c.seedCost),buyQty=Math.min(qty,available,affordable);if(available<1){say(c.name+" is out of stock until the next restock.");return}if(affordable<1){say("Not enough coins.");return}state.coins-=c.seedCost*buyQty;state.shop.stock[id]-=buyQty;state.seeds[id]=(state.seeds[id]||0)+buyQty;state.selected=id;state.selectedType="seed";render();save();say("Bought "+buyQty+" "+c.name+" seed"+(buyQty===1?"":"s")+(buyQty<qty?" (limited by stock or coins).":"."))}
function quickBuyGear(id){var g=gear(id),stock=gearStockLeft(id),max=Math.min(stock,Math.floor(state.coins/g.cost)),bundle=g.bundle||1;if(max<1){say(stock<1?g.name+" is out of stock.":"Not enough coins for "+g.name+".");return}var raw=prompt("How many "+g.name+" purchase"+(max===1?"":"s")+" do you want? Max: "+max+(bundle>1?". Each purchase gives "+bundle+".":""),max);if(raw===null)return;var qty=Math.floor(Number(raw));if(!qty||qty<1){say("Quick buy cancelled.");return}buyGear(id,qty)}
function buyGear(id,qty){var g=gear(id);ensureGearStock();qty=Math.max(1,Math.floor(Number(qty)||1));var stock=gearStockLeft(id),affordable=Math.floor(state.coins/g.cost),buyQty=Math.min(qty,stock,affordable),bundle=g.bundle||1,totalItems=buyQty*bundle;if(stock<1){say(g.name+" is out of stock until the next restock.");return}if(affordable<1){say("Not enough coins for "+g.name+".");return}state.coins-=g.cost*buyQty;state.gearShop.stock[id]-=buyQty;state.gear[id]=(state.gear[id]||0)+totalItems;state.selected=id;state.selectedType="gear";render();save();say("Bought "+totalItems+" "+g.name+(totalItems===1?"":"s")+(buyQty<qty?" (limited by stock or coins).":"."))}
function selectSeed(id){state.selected=id;state.selectedType="seed";drawSelected();drawPlots();save();say("Selected "+crop(id).name+" seed.")}
function selectGear(id){state.selected=id;state.selectedType="gear";drawSelected();drawPlots();save();say("Selected "+gear(id).name+".")}
function drawPetShop(){if(!el.petShop)return;ensureEggStock();state.equippedPets=normalizeEquippedPets(state.equippedPets,state.pets);el.petShop.innerHTML="";var bonus=petBonuses();var timer=row("\u23F1","Egg Restock: "+time(state.eggShop.nextAt-Date.now()),"Shared limited egg stock refreshes every 10 minutes. More expensive eggs appear less often.");timer.classList.add("restock-item");el.petShop.appendChild(timer);EGGS.forEach(function(egg){var stock=eggStockLeft(egg.id),canBuy=stock>0&&state.coins>=egg.cost;var item=row(egg.icon,egg.name,egg.desc+" Cost: "+num(egg.cost)+" coins - Stock: "+stock);item.querySelector(".actions").append(btn(stock>0?"Buy Egg":"Out",!canBuy,function(){buyEgg(egg.id)}));el.petShop.appendChild(item)});var summary=row("\uD83D\uDC3E","Active Pets "+state.equippedPets.length+" / "+PET_EQUIP_MAX,"Only equipped pets walk in the garden and give bonuses. Extra pets stay in your inventory.");el.petShop.appendChild(summary);var bonusRow=row("\u2728","Equipped Pet Bonuses","Gold +"+Math.round(bonus.gold*100)+"% - Rainbow +"+Math.round(bonus.rainbow*100)+"% - Weather +"+Math.round(bonus.weather*100)+"% - Coins +"+Math.round(bonus.coins*100)+"% - Growth +"+Math.round(bonus.speed*100)+"% - Yield +"+bonus.yield+" - Harvests +"+bonus.harvests);el.petShop.appendChild(bonusRow);el.petShop.appendChild(row("\u2B06","Pet Levels","Duplicates raise that pet type's level. Each level improves passive pet abilities by 12%; cooldown pets also recharge faster."));Object.keys(state.pets||{}).forEach(function(id){var count=state.pets[id]||0,p=PETS[id],level=petLevel(id),equipped=equippedCount(id),stored=count-equipped;if(!p||!count)return;var cooldown=id==="nightOwl"?" - Cooldown: "+time(Math.round(NIGHT_OWL_MS*petCooldownScale(id))):"",item=row(p.icon,p.name+" x"+count+" - Lv "+level,p.rarity+" - Equipped: "+equipped+" - Inventory: "+stored+" - "+p.desc+" - Power: "+Math.round(petScale(id)*100)+"%"+cooldown,p.rarity);item.querySelector(".actions").append(btn("Equip",state.equippedPets.length>=PET_EQUIP_MAX||equipped>=count,function(){equipPet(id)}),btn("Unequip",equipped<1,function(){unequipPet(id)}));el.petShop.appendChild(item)})}
function buyEgg(id){var egg=EGGS.find(function(e){return e.id===id});ensureEggStock();if(!egg){say("That egg is unavailable.");return}if(eggStockLeft(id)<1){say(egg.name+" is out of stock until the next restock.");return}if(state.coins<egg.cost){say("Not enough coins for that egg.");return}state.coins-=egg.cost;state.eggShop.stock[id]--;var petId=pickFrom(egg.pool),pet=PETS[petId];addPet(petId);render();save();showEgg(egg,pet);say("Hatched "+pet.name+"! "+pet.name+" is now Lv "+petLevel(petId)+".")}
function showEgg(egg,pet){if(!el.eggModal||!el.eggResult)return;el.eggTitle.textContent=egg.name;el.eggSubtitle.textContent="Crack... crack...";el.eggResult.innerHTML="<div class='pet-card rarity-"+pet.rarity.toLowerCase()+"'><span class='pet-icon'>"+pet.icon+"</span><strong>"+pet.name+"</strong><small>"+pet.rarity+"</small><p>"+pet.desc+"</p></div>";el.eggModal.classList.add("open");el.eggModal.setAttribute("aria-hidden","false");setTimeout(function(){if(el.eggSubtitle)el.eggSubtitle.textContent="A new pet joined your garden!"},650)}
function closeEgg(){if(!el.eggModal)return;el.eggModal.classList.remove("open");el.eggModal.setAttribute("aria-hidden","true")}
function drawInv(){state.equippedPets=normalizeEquippedPets(state.equippedPets,state.pets);el.inventory.innerHTML="";var any=false;CROPS.forEach(function(c){var seeds=state.seeds[c.id]||0;if(!seeds)return;any=true;var item=row(c.icon,c.name,"Rarity: "+c.rarity+" - Seeds: "+seeds+" - Harvested: 0",c.rarity);item.querySelector(".actions").append(btn("Select Seed",seeds<1,function(){selectSeed(c.id)}),btn("Sell",true,function(){}));el.inventory.appendChild(item)});Object.keys(state.crops).forEach(function(key){var count=state.crops[key]||0,parsed=parseInventoryKey(key),c=crop(parsed.id);if(!count||!c)return;any=true;var value=cropSaleValue(c,parsed.mutations,parsed.weight);var item=row(c.icon,cropDisplayName(c,parsed.mutations),"Rarity: "+c.rarity+" - Weight: "+weightLabel(parsed.weight)+" ("+weightMultiplier(parsed.weight).toFixed(2)+"x) - Harvested: "+count+" - Value: "+num(value)+" each",c.rarity);item.querySelector(".title").insertAdjacentHTML("beforeend",mutationBadges(parsed.mutations));item.querySelector(".actions").append(btn("Sell",false,function(){sell(key)}));el.inventory.appendChild(item)});GEAR.forEach(function(g){var count=state.gear[g.id]||0;if(!count)return;any=true;var item=row(g.icon,g.name,"Gear owned: "+count+" - "+g.desc);item.querySelector(".actions").append(btn("Select",false,function(){selectGear(g.id)}));el.inventory.appendChild(item)});Object.keys(state.pets||{}).forEach(function(id){var count=state.pets[id]||0,p=PETS[id],equipped=equippedCount(id),stored=count-equipped;if(!p||!count)return;any=true;var item=row(p.icon,p.name+" x"+count+" - Lv "+petLevel(id),p.rarity+" pet - Equipped: "+equipped+" - Inventory: "+stored+" - Power: "+Math.round(petScale(id)*100)+"% - "+p.desc,p.rarity);item.querySelector(".actions").append(btn("Equip",state.equippedPets.length>=PET_EQUIP_MAX||equipped>=count,function(){equipPet(id)}),btn("Unequip",equipped<1,function(){unequipPet(id)}));el.inventory.appendChild(item)});if(!any)el.inventory.appendChild(row("\uD83E\uDDFA","Empty basket","Harvest crops or buy gear to fill your inventory."))}
function sell(id){var c=crop(id),count=state.crops[id]||0;if(!count){say("No crops to sell.");return}state.crops[id]=0;var parsed=parseInventoryKey(id),c=crop(parsed.id),earned=count*cropSaleValue(c,parsed.mutations,parsed.weight);state.coins+=earned;state.stats.coinsEarnedToday+=earned;state.stats.coinsEarned+=earned;render();save();pulse(el.coins);say("Sold "+count+" "+weightLabel(parsed.weight)+" "+cropDisplayName(c,parsed.mutations)+" for "+num(earned)+" coins.")}
function sellAll(){var total=0,items=0;Object.keys(state.crops).forEach(function(key){var count=state.crops[key]||0,parsed=parseInventoryKey(key),c=crop(parsed.id);if(count&&c){total+=count*cropSaleValue(c,parsed.mutations,parsed.weight);items+=count;state.crops[key]=0}});if(!total){say("No harvested crops to sell yet.");return}state.coins+=total;state.stats.coinsEarnedToday+=total;state.stats.coinsEarned+=total;render();save();pulse(el.coins);say("Sold "+items+" crops for "+num(total)+" coins.")}
function rollDaily(){var d=today();if(state.daily.date===d&&state.daily.quests&&state.daily.quests.length)return;state.daily.date=d;state.stats.plantedToday=0;state.stats.coinsEarnedToday=0;state.daily.quests=[{id:"plant3",kind:"plant",target:3,title:"Plant 3 seeds",claimed:false,pack:"Starter Seed Pack"},{id:"earn100",kind:"earn",target:100,title:"Earn 100 coins from selling crops",claimed:false,pack:"Fruit Seed Pack"},{id:"plant8",kind:"plant",target:8,title:"Plant 8 seeds",claimed:false,pack:"Rare Seed Pack"}]}
function questProgress(q){return q.kind==="plant"?state.stats.plantedToday:state.stats.coinsEarnedToday}
function drawQuests(){el.quests.innerHTML="";state.daily.quests.forEach(function(q){var p=Math.min(q.target,questProgress(q)),done=p>=q.target;var item=row(done?"\uD83C\uDF81":"\uD83D\uDCCB",q.title,"Progress: "+p+"/"+q.target+" - Prize: "+q.pack);item.querySelector(".actions").append(btn(q.claimed?"Claimed":done?"Claim":"Working",q.claimed||!done,function(){claimQuest(q.id)}));el.quests.appendChild(item)})}
function eventWeek(){var start=new Date(Date.UTC(2026,0,5));return Math.floor((Date.now()-start.getTime())/(7*24*60*60*1000))}
function eventItem(id){return EVENT_ITEMS.find(function(item){return item.id===id})}
function eventRoll(slot,id,salt){return stockRoll(slot,"event_"+id,salt)}
function rollEventStock(slot){slot=slot||eventShopSlot();var stock={};if(activeNightEvent())EVENT_ITEMS.forEach(function(item){if(eventRoll(slot,item.id,29)<item.chance){var min=item.min||1,max=item.max||min;stock[item.id]=min+Math.floor(eventRoll(slot,item.id,73)*(max-min+1))}});state.eventShop={stock:stock,slot:slot,nextAt:eventSlotEnd(slot)};return stock}
function ensureEventStock(){if(!state.eventShop)state.eventShop={stock:{},slot:0,nextAt:0};if(!state.eventShop.stock)state.eventShop.stock={};var slot=eventShopSlot();if(state.eventShop.slot!==slot||!state.eventShop.nextAt)rollEventStock(slot)}
function eventStockLeft(id){ensureEventStock();return state.eventShop.stock[id]||0}
function nightPackSeed(){var roll=Math.random()*100;if(roll<50)return"orchid";if(roll<75)return"lavender";if(roll<90)return"mulberry";if(roll<95)return"nightshade";if(roll<98.5)return"blackapple";return"darkblossom"}
function buyEventItem(id){var item=eventItem(id),stock=eventStockLeft(id);if(!item){say("That event item is unavailable.");return}if(stock<1){say(item.name+" is out of stock this week.");return}if(state.coins<item.cost){say("Not enough coins for "+item.name+".");return}state.coins-=item.cost;state.eventShop.stock[id]--;if(item.kind==="seed"){state.seeds[id]=(state.seeds[id]||0)+1;state.selected=id;state.selectedType="seed";say("Bought and selected "+crop(id).name+" seed.")}else if(item.kind==="pet"){addPet(id);say("Bought "+PETS[id].name+". It is now Lv "+petLevel(id)+".")}else{var seed=nightPackSeed();state.seeds[seed]=(state.seeds[seed]||0)+1;showSeedPack("Night Seed Pack",[seed]);say("Night Seed Pack opened.")}render();save()}
function applyNightOwl(){var count=activePetCounts().nightOwl||0;if(!count)return;if(!state.event)state.event={owlNextAt:0};var now=Date.now();if(state.event.owlNextAt&&now<state.event.owlNextAt)return;var blessed=0,plants=state.plots.map(function(p,i){return p&&!((p.mutations||[]).indexOf("moonlit")>=0)?i:null}).filter(function(i){return i!==null});for(var n=0;n<count&&plants.length;n++){var pick=plants.splice(Math.floor(Math.random()*plants.length),1)[0];addMutation(state.plots[pick].mutations,"moonlit");blessed++}state.event.owlNextAt=now+Math.round(NIGHT_OWL_MS*petCooldownScale("nightOwl"));if(blessed)say("Owl blessed "+blessed+" plant"+(blessed===1?"":"s")+" with Moonlit.");save()}
function drawEvents(){if(!el.events)return;ensureEventStock();el.events.innerHTML="";var timer=row("\u23F1","Event Shop Restock: "+time(state.eventShop.nextAt-Date.now()),"Shared event stock refreshes every 10 minutes, at the same time for everyone.");timer.classList.add("restock-item");el.events.appendChild(timer);if(!activeNightEvent()){el.events.appendChild(row("\uD83D\uDCC5","Weekly Events","Events change once a week. Week "+eventWeek()+" is currently active."));el.events.appendChild(row("\uD83C\uDF3F","No Event This Week","This week's event slot is empty. Check back after the weekly rotation."));return}el.events.appendChild(row("\uD83C\uDF19","Nighttime Event","Night Time weather happens for the first 5 minutes of every hour. While it is active, plants can gain Moonlit, a x4 value mutation."));EVENT_ITEMS.forEach(function(item){var stock=eventStockLeft(item.id),label=stock>0?"Buy "+num(item.cost):"Out";var meta=item.desc+" Cost: "+num(item.cost)+" coins - Stock: "+stock+" - Stock chance: "+(item.chance*100)+"%";var entry=row(item.icon,item.name,meta,item.id==="moonbloom"?"Prismatic":item.id==="moonblossom"||item.id==="nightOwl"?"Divine":"");entry.querySelector(".actions").append(btn(label,stock<1||state.coins<item.cost,function(){buyEventItem(item.id)}));el.events.appendChild(entry)})}
function claimQuest(id){var q=state.daily.quests.find(function(x){return x.id===id});if(!q||q.claimed||questProgress(q)<q.target){say("That quest is not ready yet.");return}q.claimed=true;var prize=seedPack(q.pack);prize.forEach(function(id){state.seeds[id]=(state.seeds[id]||0)+1});render();save();showSeedPack(q.pack,prize);say(q.pack+" opened.")}
function pickFrom(pool){return pool[Math.floor(Math.random()*pool.length)]}
function seedPack(pack){var common=["carrot","strawberry","lemon","blueberry","candyapple"],fruit=["strawberry","blueberry","apple","cherry","banana","grape","cloudberry"],rare=["watermelon","banana","grape","kiwi","peach","pineapple","papaya","emberfig"],premium=["mango","bamboo","pomegranate","dragonfruit","cacao","moonmelon","lychee","royalkiwi","prismplum"];if(pack==="Rare Seed Pack")return [pickFrom(rare),pickFrom(rare),Math.random()<.22?pickFrom(premium):pickFrom(fruit)];if(pack==="Fruit Seed Pack")return [pickFrom(fruit),pickFrom(fruit),Math.random()<.18?pickFrom(rare):pickFrom(common)];return [pickFrom(common),pickFrom(common),Math.random()<.12?pickFrom(fruit):pickFrom(common)]}
function showSeedPack(pack,prize){if(!el.packModal||!el.packCards)return;el.packTitle.textContent=pack;el.packSubtitle.textContent="Tearing open the pack...";el.packCards.innerHTML="";el.packModal.classList.add("open");el.packModal.setAttribute("aria-hidden","false");prize.forEach(function(id,index){var c=crop(id);var card=document.createElement("div");card.className="pack-card rarity-"+c.rarity.toLowerCase();card.style.animationDelay=index*.22+"s";card.innerHTML="<span class='pack-icon'>"+c.icon+"</span><strong>"+c.name+"</strong><small>"+c.rarity+(c.packOnly?" - Exclusive":"")+"</small>";el.packCards.appendChild(card)});setTimeout(function(){if(el.packSubtitle)el.packSubtitle.textContent="You found "+prize.length+" seeds!"},650)}
function closeSeedPack(){if(!el.packModal)return;el.packModal.classList.remove("open");el.packModal.setAttribute("aria-hidden","true")}
function leaderboardScore(){return {name:(state.leaderboard.name||"Gardener").slice(0,24),coins:Math.floor(state.coins),coinsEarned:Math.floor(state.stats.coinsEarned||0),seedsPlanted:Math.floor(state.stats.seedsPlanted||0)}}
function drawLeaderboard(){if(!el.leaderboard)return;el.leaderboard.innerHTML="";var score=leaderboardScore();var mine=row("\uD83C\uDFC6","Your Score","Coins: "+num(score.coins)+" - Coins earned: "+num(score.coinsEarned)+" - Seeds planted: "+num(score.seedsPlanted));mine.querySelector(".actions").append(btn("Submit",false,submitLeaderboard));el.leaderboard.appendChild(mine);el.leaderboard.appendChild(row("\uD83D\uDCE1","Online Status",state.leaderboard.status||"Run server.js to enable online rankings."));var rows=state.leaderboard.rows||[];if(!rows.length){el.leaderboard.appendChild(row("\uD83D\uDCCB","No scores loaded","Refresh the leaderboard after starting the online server."));return}rows.forEach(function(r,i){el.leaderboard.appendChild(row("#"+(i+1),r.name||"Gardener","Coins: "+num(r.coins||0)+" - Coins earned: "+num(r.coinsEarned||0)+" - Seeds planted: "+num(r.seedsPlanted||0)))})}
function leaderboardUrl(){var host=location.hostname;if(location.protocol.indexOf("http")!==0||host.indexOf("github.io")>=0)return "";return "/api/leaderboard"}
function submitLeaderboard(){var url=leaderboardUrl();if(!url){state.leaderboard.status="Open the game through server.js to submit online scores.";drawLeaderboard();say("Leaderboard server is not running.");return}var name=prompt("Leaderboard name:",state.leaderboard.name||"Gardener");if(name===null)return;state.leaderboard.name=(name.trim()||"Gardener").slice(0,24);save();fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(leaderboardScore())}).then(function(r){if(!r.ok)throw new Error("offline");return r.json()}).then(function(data){state.leaderboard.rows=data.rows||[];state.leaderboard.status="Score submitted.";render();save();say("Leaderboard score submitted.")}).catch(function(){state.leaderboard.status="Online leaderboard unavailable. Start server.js and try again.";drawLeaderboard();say("Leaderboard unavailable.")})}
function loadLeaderboard(){var url=leaderboardUrl();if(!url){state.leaderboard.status="Open the game through server.js to load online scores.";drawLeaderboard();say("Leaderboard server is not running.");return}fetch(url).then(function(r){if(!r.ok)throw new Error("offline");return r.json()}).then(function(data){state.leaderboard.rows=data.rows||[];state.leaderboard.status="Leaderboard refreshed.";render();save();say("Leaderboard refreshed.")}).catch(function(){state.leaderboard.status="Online leaderboard unavailable. Start server.js and try again.";drawLeaderboard();say("Leaderboard unavailable.")})}
function drawUpgrades(){el.upgrades.innerHTML="";upgradeRow("plots","More Plots","Unlock extra garden plots.","\u25A6");upgradeRow("speed","Growth Speed","Shorten every new crop timer.","\uD83D\uDCA7");upgradeRow("yield","Harvest Yield","Gain extra crops from each harvest.","\u25A3")}
function upgradeRow(type,title,desc,icon){var current=up(type),n=next(type),meta=desc+" Current: "+current.label+" - "+current.effect;if(n)meta+=". Next: "+n.effect;var item=row(icon,title,meta);item.querySelector(".actions").append(btn(n?"Buy "+n.cost:"Max",!n||state.coins<n.cost,function(){buyUp(type)}));el.upgrades.appendChild(item)}
function buyUp(type){var n=next(type);if(!n){say("That upgrade is already maxed.");return}if(state.coins<n.cost){say("Not enough coins for that upgrade.");return}state.coins-=n.cost;state.up[type]=clampUpgradeLevel(state.up[type])+1;fitPlots();render();save();say("Upgrade purchased: "+up(type).label+".")}
function drawRebirth(){if(!el.rebirth)return;var count=rebirthCount(),cost=rebirthCost(),multi=rebirthSaleMultiplier();el.rebirth.innerHTML="";el.rebirth.appendChild(row("\u267B","Rebirths: "+count,"Permanent crop sale multiplier: x"+multi+". Next rebirth raises it to x"+(multi+1)+"."));var reset=row("\u2728","Next Rebirth","Cost: "+num(cost)+" coins. Rebirth resets coins, seeds, crops, gear, pets, upgrades, and planted plots.");reset.querySelector(".actions").append(btn("Rebirth",state.coins<cost,function(){doRebirth()}));el.rebirth.appendChild(reset);el.rebirth.appendChild(row("\uD83C\uDF31","Fresh Start","After rebirthing, your garden starts over with 40 coins while your rebirth multiplier stays forever."))}
function doRebirth(){var cost=rebirthCost(),nextCount=rebirthCount()+1;if(state.coins<cost){say("You need "+num(cost)+" coins to rebirth.");return}if(!confirm("Rebirth for "+num(cost)+" coins? This resets your active garden progress but keeps permanent rebirths."))return;var keepLeaderboard=Object.assign({},state.leaderboard||{}),keepMusic=!!state.musicOn;state=fresh();state.rebirths=nextCount;state.musicOn=keepMusic;state.leaderboard=keepLeaderboard;fitPlots();rollDaily();render();save();say("Rebirth complete. Crop sales are now x"+rebirthSaleMultiplier()+".")}
function drawAdmin(){if(!el.admin)return;if(!adminUnlocked){el.admin.innerHTML="<div class='admin-lock'><p>Enter the admin password to unlock grants.</p><input id='adminPassword' type='password' placeholder='Password' autocomplete='off'><button id='adminUnlock' type='button'>Unlock</button></div>";el.admin.querySelector("#adminUnlock").onclick=unlockAdmin;return}el.admin.innerHTML="<div class='admin-grid'><label>Coins<input id='adminCoins' type='number' min='1' step='1' placeholder='Amount'></label><button id='adminGiveCoins' type='button'>Give Coins</button><label>Item Type<select id='adminItemType'><option value='seeds'>Seeds</option><option value='crops'>Crops</option><option value='gear'>Gear</option></select></label><label>Item<select id='adminItemId'></select></label><label>Amount<input id='adminItemAmount' type='number' min='1' step='1' value='1'></label><button id='adminGiveItem' type='button'>Give Item</button><label>Pet<select id='adminPetId'></select></label><label>Amount<input id='adminPetAmount' type='number' min='1' step='1' value='1'></label><button id='adminGivePet' type='button'>Give Pet</button></div>";fillAdminOptions();el.admin.querySelector("#adminItemType").onchange=fillAdminItemOptions;el.admin.querySelector("#adminGiveCoins").onclick=adminGiveCoins;el.admin.querySelector("#adminGiveItem").onclick=adminGiveItem;el.admin.querySelector("#adminGivePet").onclick=adminGivePet}
function unlockAdmin(){var input=el.admin&&el.admin.querySelector("#adminPassword");if(!input||input.value!==ADMIN_PASSWORD){say("Wrong admin password.");return}adminUnlocked=true;drawAdmin();say("Admin panel unlocked.")}
function adminAmount(id){var input=el.admin&&el.admin.querySelector(id),value=Math.floor(Number(input&&input.value));return value>0?value:0}
function adminOption(value,text){return "<option value='"+value+"'>"+text+"</option>"}
function fillAdminOptions(){fillAdminItemOptions();var petSelect=el.admin.querySelector("#adminPetId");petSelect.innerHTML=Object.keys(PETS).sort(function(a,b){return PETS[a].name.localeCompare(PETS[b].name)}).map(function(id){return adminOption(id,PETS[id].name+" ("+PETS[id].rarity+")")}).join("")}
function fillAdminItemOptions(){var type=el.admin.querySelector("#adminItemType").value,select=el.admin.querySelector("#adminItemId");if(type==="gear"){select.innerHTML=GEAR.map(function(g){return adminOption(g.id,g.name)}).join("");return}select.innerHTML=CROPS.slice().sort(function(a,b){return a.name.localeCompare(b.name)}).map(function(c){return adminOption(c.id,c.name+" ("+c.rarity+")")}).join("")}
function adminGiveCoins(){var amount=adminAmount("#adminCoins");if(!amount){say("Enter a coin amount first.");return}state.coins+=amount;render();save();pulse(el.coins);say("Admin granted "+num(amount)+" coins.")}
function adminGiveItem(){var type=el.admin.querySelector("#adminItemType").value,id=el.admin.querySelector("#adminItemId").value,amount=adminAmount("#adminItemAmount");if(!amount){say("Enter an item amount first.");return}if(type==="gear"){state.gear[id]=(state.gear[id]||0)+amount;say("Admin granted "+amount+" "+gear(id).name+".")}else if(type==="crops"){var c=crop(id),key=inventoryKey(id,[],1);state.crops[key]=(state.crops[key]||0)+amount;say("Admin granted "+amount+" "+c.name+" crops.")}else{var seed=crop(id);state.seeds[id]=(state.seeds[id]||0)+amount;state.selected=id;state.selectedType="seed";say("Admin granted "+amount+" "+seed.name+" seeds.")}render();save()}
function adminGivePet(){var id=el.admin.querySelector("#adminPetId").value,amount=adminAmount("#adminPetAmount"),pet=PETS[id];if(!pet||!amount){say("Choose a pet and amount first.");return}state.pets[id]=(state.pets[id]||0)+amount;state.petLevels[id]=Math.min(PET_LEVEL_MAX,Math.max(1,state.petLevels[id]||1)+amount);state.equippedPets=autoEquipPets(state.equippedPets,state.pets);render();save();say("Admin granted "+amount+" "+pet.name+" pet"+(amount===1?"":"s")+".")}
function row(icon,title,meta,rarity){var d=document.createElement("div");var rarityClass=rarity?" rarity-"+rarity.toLowerCase().replace(/[^a-z0-9]+/g,"-"):"";d.className="item"+rarityClass;var badge=rarity?"<span class='badge'>"+rarity+"</span>":"";d.innerHTML="<span class='icon'>"+icon+"</span><div><p class='title'>"+title+badge+"</p><p class='meta'>"+meta+"</p></div><div class='actions'></div>";return d}
function btn(text,disabled,fn){var b=document.createElement("button");b.type="button";b.textContent=text;b.disabled=disabled;b.onclick=fn;return b}
function say(t){el.log.textContent=t;pulse(el.log)}
function pulse(x){x.classList.remove("pop");void x.offsetWidth;x.classList.add("pop")}
function time(ms){var s=Math.max(0,Math.ceil(ms/1000)),m=Math.floor(s/60);s=s%60;return m?m+"m "+String(s).padStart(2,"0")+"s":s+"s"}
function num(n){n=Math.floor(Number(n)||0);var abs=Math.abs(n),units=[{v:1e36,s:"ud"},{v:1e33,s:"d"},{v:1e30,s:"n"},{v:1e27,s:"o"},{v:1e24,s:"sp"},{v:1e21,s:"sx"},{v:1e18,s:"qi"},{v:1e15,s:"q"},{v:1e12,s:"t"},{v:1e9,s:"b"},{v:1e6,s:"m"},{v:1e3,s:"k"}];for(var i=0;i<units.length;i++){if(abs>=units[i].v){var value=n/units[i].v,decimals=Math.abs(value)>=100?0:Math.abs(value)>=10?1:2;return Number(value.toFixed(decimals)).toString()+units[i].s}}return n.toLocaleString()}
})();






